name: CI with symfony/validator 6.4 dependency

on: [push, pull_request]

jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.3', '8.4', '8.5']
        include:
          - php-version: '8.6'
            experimental: true
    steps:
      # Download code from repository
      - name: Checkout code
        uses: actions/checkout@v6

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      # Setup Composer
      - name: Setup Composer
        run: composer install

      # Force symfony/validator 6.4 for the run
      - name: Force symfony/validator 6.4
        run: composer require symfony/validator:"^6.4"

      # Show which symfony/validator version has been installed
      - name: Show installed symfony/validator
        run: composer show symfony/validator

      # Run linter
      - name: Run linter
        run: composer lint -- --test -v

      # Run static analyzer
      - name: Run static analyzer
        run: composer stan

      # Run tests
      - name: Run tests
        run: composer test
